name: Add New Game

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the game'
        required: true
      iframe_url:
        description: 'URL of the game iframe'
        required: true
      screenshot:
        description: 'URL of the game screenshot'
        required: true

jobs:
  add_game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create game file
        run: |
          echo "---" > _games/${{ inputs.title }}.md
          echo "title: ${{ inputs.title }}" >> _games/${{ inputs.title }}.md
          echo "iframe_url: ${{ inputs.iframe_url }}" >> _games/${{ inputs.title }}.md
          echo "---" >> _games/${{ inputs.title }}.md

      - name: Save screenshot
        run: |
          mkdir -p assets/games
          mv ${{ inputs.screenshot }} assets/games/${{ inputs.title }}.png

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add new game: ${{ inputs.title }}"
          git push origin main
